import eventlet
eventlet.monkey_patch()

workers = 1          # Eventlet — только 1 worker, он сам асинхронный
worker_class = 'eventlet'
worker_connections = 1000
bind = '0.0.0.0:10000'
timeout = 120
keepalive = 5
